@baseUrl = http://localhost:5000

### GET
GET {{baseUrl}}

### Create User
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "FullName": "John Doe",
    "Email": "johndoe@email.com",
    "Password": "JohnPassword"
}