@baseUrl = http://localhost:5000
@cookie = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxY2NjYjgyLWVjYjktNGNkYS05YWIzLTVmOWUxMDU4NmYyZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImpvaG5kb2VAZW1haWwuY29tIiwiZXhwIjoxNzkxNDA5OTE5LCJpc3MiOiJSZXNlcnZlaUFwaSIsImF1ZCI6IlJlc2VydmVpQXBpIn0.VM8IG3eJVjm92TcpixD7iSNcUoiSkD5TXXE_nwIS7e8

### GET
GET {{baseUrl}}

### Create User
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "Email": "johndoe@email.com",
    "Password": "JohnPassword"
}

### Login User
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "Email": "johndoe@email.com",
    "Password": "JohnPassword"
}

### Create Professional Profile
POST {{baseUrl}}/api/professionals
Content-Type: application/json
Cookie: jwt={{cookie}}

{
    "Username": "feitozabruno",
    "FullName": "Bruno Feitoza",
    "Specialty": "Desenvolvedor de Software",
    "BusinessName": "GitHub",
    "PhoneNumber": "67987654321",
    "Bio": "Especializado em software manutenível, testado e bem documentado.",
    "AddressCep": "79800-000",
    "AddressStreet": "Rua Zuckenberg",
    "AddressNumber": "789",
    "AddressNeightborhood": "Centro",
    "AddressCity": "São Francisco",
    "AddressState": "MS",
    "AddressComplement": "Próximo a empresa Meta"
}

### Read Professional Profile
GET {{baseUrl}}/api/professionals/me
Cookie: jwt={{cookie}}

### Read Professional Profile with Username
GET {{baseUrl}}/api/professionals/feitozabruno

### Create Professional Availabilites
POST {{baseUrl}}/api/availabilities
Content-Type: application/json
Cookie: jwt={{cookie}}

[
    {
        "dayOfWeek": 1,
        "startTime": "09:00:00",
        "endTime": "13:00:00"
    },
    {
        "dayOfWeek": 1,
        "startTime": "15:00:00",
        "endTime": "19:00:00"
    },
    {
        "dayOfWeek": 2,
        "startTime": "09:00:00",
        "endTime": "13:00:00"
    },
    {
        "dayOfWeek": 2,
        "startTime": "15:00:00",
        "endTime": "19:00:00"
    },
    {
        "dayOfWeek": 3,
        "startTime": "09:00:00",
        "endTime": "13:00:00"
    },
    {
        "dayOfWeek": 3,
        "startTime": "15:00:00",
        "endTime": "19:00:00"
    },
    {
        "dayOfWeek": 4,
        "startTime": "09:00:00",
        "endTime": "13:00:00"
    },
    {
        "dayOfWeek": 4,
        "startTime": "15:00:00",
        "endTime": "19:00:00"
    },
    {
        "dayOfWeek": 5,
        "startTime": "09:00:00",
        "endTime": "13:00:00"
    },
    {
        "dayOfWeek": 5,
        "startTime": "15:00:00",
        "endTime": "19:00:00"
    }
]

### Read Professional Availabilites
GET {{baseUrl}}/api/availabilities/me
Cookie: jwt={{cookie}}

### Create Professional Services
POST {{baseUrl}}/api/services
Content-Type: application/json
Cookie: jwt={{cookie}}

{
    "name": "Terapia",
    "price": 350,
    "durationMinutes": 60,
    "description": "Sessão de terapia comportamental."
}

### Read Professional Services
GET {{baseUrl}}/api/services/me
Cookie: jwt={{cookie}}

### Read Professional Available Slots
GET {{baseUrl}}/api/professionals/04118d9e-5db9-4cc3-ad68-72f94884f27f/available-slots?serviceId=30d6cbe7-11e4-4cdf-8d2b-0401e5954be4&date=2026-09-08

### Create Appointment
POST {{baseUrl}}/api/appointments
Content-Type: application/json

{
    "professionalId": "04118d9e-5db9-4cc3-ad68-72f94884f27f",
    "serviceId": "30d6cbe7-11e4-4cdf-8d2b-0401e5954be4",
    "clientName": "Elon Musk",
    "clientEmail": "elonmusk@hotmail.com",
    "clientPhone": "10987654321",
    "startTime": "2026-09-08T13:00:00+00:00"
}

### Cancel Appointment By Professional Logged
PATCH {{baseUrl}}/api/appointments/5437ecec-e90d-47b7-b715-408a70fbe20b/cancel-by-professional
Cookie: jwt={{cookie}}

### Cancel Appointment By Client AccessToken
PATCH {{baseUrl}}/api/appointments/dce2357b-c7bd-4472-b948-7c9e9ec6683e/cancel-by-client?accessToken=e444d1221a544dd5a43d679908091bb8

### Upload Professional Avatar Photo
PATCH {{baseUrl}}/api/professionals/me/photo
Cookie: jwt={{cookie}}

### Get Paged All Professionals
GET {{baseUrl}}/api/professionals?page=1&pageSize=10