services:
  database:
    container_name: "postgres-dev"
    image: "postgres:17.5-alpine3.22"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"

  mailcatcher:
    container_name: "mailcatcher-dev"
    image: "dockage/mailcatcher:0.9.0"
    ports:
      - "1080:1080"
      - "1025:1025"
